export const INTERNAL_TOKEN_PENDING = 'INTERNAL_TOKEN_PENDING';
export const INTERNAL_TOKEN_SUCCESS = 'INTERNAL_TOKEN_SUCCESS';
export const INTERNAL_TOKEN_FAIL = 'INTERNAL_TOKEN_FAIL';

export const GET_ADMIN_TOKEN_PENDING = 'GET_ADMIN_TOKEN_PENDING';
export const GET_ADMIN_TOKEN_SUCCESS = 'GET_ADMIN_TOKEN_SUCCESS';
export const GET_ADMIN_TOKEN_FAIL = 'GET_ADMIN_TOKEN_FAIL';

export const GET_VENDOR_CATEGORIES_PENDING = 'GET_VENDOR_CATEGORIES_PENDING';
export const GET_VENDOR_CATEGORIES_SUCCESS = 'GET_VENDOR_CATEGORIES_SUCCESS';
export const GET_VENDOR_CATEGORIES_FAIL = 'GET_VENDOR_CATEGORIES_FAIL';

export const GET_CATEGORIES_PENDING = 'GET_CATEGORIES_PENDING';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

export const GET_VENDORS_LIST_PENDING = 'GET_VENDORS_LIST_PENDING';
export const GET_VENDORS_LIST_SUCCESS = 'GET_VENDORS_LIST_SUCCESS';
export const GET_VENDORS_LIST_FAIL = 'GET_VENDORS_LIST_FAIL';

export const GET_PRODUCTS_FOR_HOME_PENDING = 'GET_PRODUCTS_FOR_HOME_PENDING';
export const GET_PRODUCTS_FOR_HOME_SUCCESS = 'GET_PRODUCTS_FOR_HOME_SUCCESS';
export const GET_PRODUCTS_FOR_HOME_FAIL = 'GET_PRODUCTS_FOR_HOME_FAIL';

export const GET_PRODUCTS_PENDING = 'GET_PRODUCTS_PENDING';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_MORE = 'GET_PRODUCTS_MORE';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

export const GET_PRODUCT_PENDING = 'GET_PRODUCT_PENDING';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL';
export const PRODUCT_ATTRIBUTE_SELECT = 'PRODUCT_ATTRIBUTE_SELECT';

export const GET_PRODUCT_COMPOSITE_PENDING = 'GET_PRODUCT_COMPOSITE_PENDING';
export const GET_PRODUCT_COMPOSITE_SUCCESS = 'GET_PRODUCT_COMPOSITE_SUCCESS';
export const GET_PRODUCT_COMPOSITE_FAIL = 'GET_PRODUCT_COMPOSITE_FAIL';
export const PRODUCT_COMPOSITE_OPTION_SELECT =
    'PRODUCT_COMPOSITE_OPTION_SELECT';

export const SIGN_UP_PENDING = 'SIGN_UP_PENDING';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';

export const SIGN_IN_PENDING = 'SIGN_IN_PENDING';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';

export const SIGN_OUT = 'SIGN_OUT';

export const GET_MEASUREMENT_PENDING = 'GET_MEASUREMENT_PENDING';
export const GET_MEASUREMENT_SUCCESS = 'GET_MEASUREMENT_SUCCESS';
export const GET_MEASUREMENT_FAIL = 'GET_MEASUREMENT_FAIL';
export const SAVE_MEASUREMENT_PENDING = 'SAVE_MEASUREMENT_PENDING';
export const SAVE_MEASUREMENT_SUCCESS = 'SAVE_MEASUREMENT_SUCCESS';
export const SAVE_MEASUREMENT_FAIL = 'SAVE_MEASUREMENT_FAIL';
export const DELETE_MEASUREMENT_PENDING = 'DELETE_MEASUREMENT_PENDING';
export const DELETE_MEASUREMENT_SUCCESS = 'DELETE_MEASUREMENT_SUCCESS';
export const DELETE_MEASUREMENT_FAIL = 'DELETE_MEASUREMENT_FAIL';

export const UPDATE_PROFILE_PENDING = 'UPDATE_PROFILE_PENDING';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';
export const PROFILE_UPDATED = 'PROFILE_UPDATED';
